[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd backend && npm install && npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[build.environment]
NODE_ENV = "production"